### ISSUE TITLE
PDF-Files: database insertation method.

### ISSUE THREAD

**Issue by bolzobrazil** [textbrowser/spot-on#22]
adding a PDF-ebook insertation method with bibliographic description data 
for Spot-On`s search tab/database to add ebooks/PDFs e.g. from: 

https://annas-archive.org/search?q=github

or one of those:

https://wiki.c3d2.de/Bibliotheken_online

**Comment by textbrowser** [comment]
Spot-On cannot save you from the computers of the future. All the secrets will be revealed and the quantum configurations will atomize the Universe.
