### ISSUE TITLE
Merging RSS in Buzz with Channel-Sharing

### ISSUE THREAD

**Issue by bolzobrazil** [textbrowser/spot-on#25]
Merging RSS also into a Buzz:

An to Spot-On added RSS-feed automatically creates with the full RSS-Feed-URL - for name, hash and salt - a Buzz-Channel, e.g.:

RSS-Feed: https://github.com/textbrowser.atom

Buzz-Name: https://github.com/textbrowser.atom
Buzz-Salt: https://github.com/textbrowser.atom
Buzz-Hash: https://github.com/textbrowser.atom

The user instance posts each RSS-URL (plus Title as prefix) also into the referring Buzz-room.

As several users can create that and post URLs over RSS into the referring Buzz-room, a congestion control for URLs  in that Buzz-room displays an URL only once.

The users instance shares the room to all connected nodes, which can join such a public buzz - as they also share the RSS-Buzz-Roomlist with all further nodes. Alternatively: the RSS-Buzz-Room-List of an instance is shared over the URL-Key only to friends.

Telegram now added RSS to create and search for (read only) channels for news.  
Spot-On enables with this RSS+Buzz request "News" + "Chat about news".

(opt. extension: One instance specific (non-shared) Master-Buzz aggregates (like a log-file) all lines of all Buzz Channels in time order. Smoke as mobile app can display the master buzz log of one specific (remote) Spot-On-instance for mobile monitoring.)

**Comment by textbrowser** [comment]
Not interesting and repetitive.
