### ISSUE TITLE
Windows-64 Spot-On-2023.12.15.zip:  TLS initialization failed

### ISSUE THREAD

**Issue by bolzobrazil** [textbrowser/spot-on#26]
The GUI interface is not connected to the Spot-On kernel:

A UI error (No functional TLS backend was found) occurred.

A UI error (QSslSocket::connectToHostEncrypted: TLS initialization failed) occurred.

spoton::slotKernelSocketError(): socket error (TLS initialization failed).

Generating SSL/TLS 2048 Bit Kernel Socket credentials is repeated and repeated.

Probably the Win-32-Version needs to be referred:
https://github.com/textbrowser/spot-on/releases/download/2023.01.15/Spot-On.zip

**Comment by textbrowser** [comment]
Works in non-Windows with OpenSSL 3. Will not redo the entire OpenSSL implementation for Windows. As stated before, a secure connection is not required. Set the key size to zero. Windows 11 has its own implementation and I don't have the interest, time, and money to fix your problem.

**Comment by textbrowser** [comment]
> openssl s_client -connect 127.0.0.1:53535
Connecting to 127.0.0.1
CONNECTED(00000003)
Can't use SSL_get_servername
depth=0 O=Spot-On Origami Self-Signed Certificate, CN=127.0.0.1
verify error:num=18:self-signed certificate
verify return:1
depth=0 O=Spot-On Origami Self-Signed Certificate, CN=127.0.0.1
verify return:1

**Comment by textbrowser** [comment]
> openssl -version     
OpenSSL 3.2.0 23 Nov 2023 (Library: OpenSSL 3.2.0 23 Nov 2023)

**Comment by textbrowser** [comment]
> uname -a
Darwin cosmos.local 22.6.0 Darwin Kernel Version 22.6.0: Tue Nov  7 21:48:06 PST 2023; root:xnu-8796.141.3.702.9~2/RELEASE_X86_64 x86_64

**Comment by textbrowser** [comment]
Windows 11 and Qt 6.5 LTS do not utilize OpenSSL. I don't know if this is false or true because I don't have the means of investigating Windows. Since you're obsessed with harassing me, you should investigate the implementation of TLS, Qt 6.5 LTS, and Windows 11.

https://learn.microsoft.com/en-us/windows/win32/com/schannel

**Comment by textbrowser** [comment]
It works with anything that's built with OpenSSL. Qt on Windows is not built with OpenSSL on Windows 11.
