### ISSUE TITLE
Bitcoin-Mining in every listener.

### ISSUE THREAD

**Issue by Sammysupport** [textbrowser/spot-on#28]
Hello,

interesting project you have to discover,

can providing a Listener be combined with an instance to mine bitcoins?

TCP over Echo can provide then a second Bitcoin network which allows to generate a second time 21 Million bitcoins by providing listeners:

- if an active and reachable Listener is a bitcoin-miner
- if the blockchain is sent over TCP of Echo
- if a Spot-On instance is the wallet,

then only the question is interesting, if bitcoins can be transferred from the Spot-Wallet to a regular Coin-Wallet?
When does mining start by opening a listener?

Sam

References:
https://developer.bitcoin.org/
https://github.com/bitcoin/bitcoin
https://github.com/libbitcoin

https://sourceforge.net/projects/easyminer/
https://www.easyminer.net/
https://github.com/luke-jr/bfgminer
https://sourceforge.net/projects/cpuminer/

https://github.com/zkSNACKs/WalletWasabi/
https://github.com/goatpig/BitcoinArmory
https://www.walletgenerator.net/
https://en.wikipedia.org/wiki/Cryptocurrency_wallet
! https://en.wikipedia.org/wiki/Bitcoin_Core  - (Qt) - https://bitcoincore.org/en/download/

https://github.com/MetacoSA/NBitcoin

https://bitcointalk.org/index.php?board=6.0
https://en.wikipedia.org/wiki/List_of_cryptocurrencies
https://en.wikipedia.org/wiki/Bitcoin
https://en.wikipedia.org/wiki/Ethereum

**Comment by Sammysupport** [comment]
**Faster Mining bound to and compensating more incomming Listener-Message-Packets:**

Just for the records, idea has been copied just two weeks later (after additionally proposing it in a referring Telegram chat):

https://repo.getmonero.org/monero-project/ccs-proposals/-/merge_requests/454
https://ccs.getmonero.org/ideas/
I2P SAMv3 eyedeekay May 4, 2024 (not me: Sammysupport)

**Comment by textbrowser** [comment]
Mining is destructive.

https://en.wikipedia.org/wiki/Environmental_effects_of_bitcoin
