### ISSUE TITLE
RSS parsing

### ISSUE THREAD

**Issue by bolzobrazil** [textbrowser/spot-on#29]
<img width="960" alt="RSS-Tool_Spot-On_Diffbot" src="https://github.com/textbrowser/spot-on/assets/86237759/14fd62a6-4e9c-4cd8-a3be-28b4f7938f8c">

Hello,

this following RSS feed shows under Spot-On Linux (2018) and Win32 (2023) RSS items in the RSS tool 
(Win64 (2024) has no working TLS, best to remove/replace the release Win64, as it shows no RSS items either on https):

https://rss.diffbot.com/rss?url=https://annas-archive.gs/search?index%3D%26page%3D1%26q%3D%26sort%3Dnewest_added

with an item URL e.g.
https://annas-archive.gs/md5/5e97cf37551a23ca25c91f356d560437

the page is rendered as an empty page 
- though items have different KiBs, so they are loaded in the RSS tool, but not shown proper in Spot-On locally view. Why?

(
Also with other website to RSS builder the same for this URL: 
https://annas-archive.gs/search?index=&page=1&q=&sort=newest_added
so probably it it not the feed format, but the website.
As the website shows in Qt Web browsers up, the parsing of Qt has to be updated?
)

After a while some imports (but still five time more failed imports) were made with a Linux 2018 version based on an updated Linux Mint system.
But still no "view locally". Has the site code to be changed for Qt Web? 
At least the PDF Export shows the URL on the page, but not the text of the site.

![spot-on_search_some_imports](https://github.com/textbrowser/spot-on/assets/86237759/494f5678-7daf-44d7-b3fd-d5bac21eac0f).

Regards Bolzo

**Comment by textbrowser** [comment]
Thanks for the report. I suspect it's an incompatibility with WebKit. If not WebKit, Qt cannot render the content in a textfield widget. I suspect the PDF is also malfunctioning. It's impossible to correct it in Qt without including a Web engine.

**Comment by textbrowser** [comment]
Utilize a Web engine with the Web server included in Spot-On until you obtain a proper build. I'm upgrading to Kubuntu 24 so I be elsewhere. Correctly compile your local version and I'm 93% confident it will work.

**Comment by textbrowser** [comment]
Yes, I be 100% correct and 100% confident now.
![SO](https://github.com/textbrowser/spot-on/assets/10701156/12a423a3-a965-4814-b7e8-cdaee85d510e)

**Comment by textbrowser** [comment]
That is a locally-viewed page existing on a passively-cooled Debian computer being viewed remotely. Let me test the PDF.

**Comment by textbrowser** [comment]
Print preview also bombastic.

![SO](https://github.com/textbrowser/spot-on/assets/10701156/bd60e302-ddbe-410e-a819-9d2c49bd4057)

**Comment by textbrowser** [comment]
PDF property generated and properly viewed.

![SO](https://github.com/textbrowser/spot-on/assets/10701156/5a663680-e2a9-4f36-aea6-f81031880deb)

**Comment by textbrowser** [comment]
> <img alt="RSS-Tool_Spot-On_Diffbot" width="960" src="https://private-user-images.githubusercontent.com/86237759/325968390-14fd62a6-4e9c-4cd8-a3be-28b4f7938f8c.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTQxNDYwODQsIm5iZiI6MTcxNDE0NTc4NCwicGF0aCI6Ii84NjIzNzc1OS8zMjU5NjgzOTAtMTRmZDYyYTYtNGU5Yy00Y2Q4LWEzYmUtMjhiNGY3OTM4ZjhjLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MjYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDI2VDE1MzYyNFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTcwNmMzMzk0MmU5Y2VmYWRmMTc3NWE1ZmJkOGE4YmQyZmE0MjQ4ZjFkZDlmMGIzOTlhYWQ1OTNiZTcwMzE3MjQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.CasXbIkPDxaGMIeK1X1KlixwPqtck34MuYd5YeyEveQ">
> 
> Hello,
> 
> this following RSS feed shows under Spot-On Linux (2018) and Win32 (2023) RSS items in the RSS tool (Win64 (2024) has no working TLS, best to remove/replace the release Win64, as it shows no RSS items either on https):
> 
> https://rss.diffbot.com/rss?url=https://annas-archive.gs/search?index%3D%26page%3D1%26q%3D%26sort%3Dnewest_added
> 
> with an item URL e.g. https://annas-archive.gs/md5/5e97cf37551a23ca25c91f356d560437
> 
> the page is rendered as an empty page
> 
>     * though items have different KiBs, so they are loaded in the RSS tool, but not shown proper in Spot-On locally view. Why?
> 
> 
> ( Also with other website to RSS builder the same for this URL: https://annas-archive.gs/search?index=&page=1&q=&sort=newest_added so probably it it not the feed format, but the website. As the website shows in Qt Web browsers up, the parsing of Qt has to be updated? )
> 
> After a while some imports (but still five time more failed imports) were made with a Linux 2018 version based on an updated Linux Mint system. But still no "view locally". Has the site code to be changed for Qt Web? At least the PDF Export shows the URL on the page, but not the text of the site.
> 
> ![spot-on_search_some_imports](https://private-user-images.githubusercontent.com/86237759/326001904-494f5678-7daf-44d7-b3fd-d5bac21eac0f.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTQxNDYwODQsIm5iZiI6MTcxNDE0NTc4NCwicGF0aCI6Ii84NjIzNzc1OS8zMjYwMDE5MDQtNDk0ZjU2NzgtN2RhZi00NGQ3LWIzZmQtZDViYWMyMWVhYzBmLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MjYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDI2VDE1MzYyNFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTQwNDEwZjlhMjBkNTQ2Mzk5ZWE0ZmEyMTYzNGY1MmNjYzU4ZTI4YjY3NzBiMzEwNDU3ZWQxNWIyOTllMDJhNmQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.e76r-9Tat_D-moiUIm2U6GLe0AUZmf5SaA393qeLKdE).
> 
> Regards Bolzo

WebKit is not available in Qt 6 LTS. WebEngine is impossible to work with in Windows. Impossible because it requires MS Studio and a gigantic amount of dependencies which you're required to maintain. Problem 1 or 2 or whatever.

Qt cannot render super pages in a plain text widget. It cannot. It will not. Let's stress this again. It will never ever. You'll be a billionaire first. So, because SO is so cute, it (consider this for a moment or two or many) supports two (two! > one?) Web engines. Actually, it supports all of them through its own Web server; returning to the two for a minute - indeed two for local content. Where else are you finding this bombastic attitude? No where. People. People!

So, utilize a real operating system or enable the Web server or spend many hours learning the world of Windows. All is remembered, all is forgiven.

**Comment by textbrowser** [comment]
The only portable solution I see for Windows people is to retract to Qt 5.15. However, I don't know if Qt 5.15 LTS lives in Windows 64. And then there is the OpenSSL maintenance too. It's too much unpaid work. You have to pay a book to read it. You're getting everything for free here. Time, support, awesome software. For free. Returning to the book. Even if it's stolen, digital, whatever; you pay for it to read it. See you.
