### ISSUE TITLE
A Twitter / Reddit like comment system.

### ISSUE THREAD

**Issue by alexlenn** [textbrowser/spot-on#31]
Hello,
proposing the following idea and feature request:

Next to the URL Key a Comment Key is established to build a Twitter / X / Reddit / Mastodon like comment system for/on URLs respective shared pages.

The app is extend for an input field to "add an URL" and a "comment for that URL" respective its hash.
The input field creates a bundle: URL Key plus Comment Key, URL + Message/Page plus Comment and hashes.

In General: The URL is shared over the URL key, the comment is shared over the Comment Key.

The URL is hashed, the message is hashed.
An index out of timestamp, URL hash and comment hash and comment key creates an index, which is shared.

It is possible to block Comment Keys from appearing in the GUI to exclude spams or unwished content creators.

Comment Keys are shared automatically with all reachable nodes in an app standard channel.

As the input field adds URL Key and Comment Key to the shared messages, all of this is distributed over the Comment-Key-Channel (including the URL Key) (or first: over the standard Auto-Channel for Comment Keys.)
(Means: Inserting an URL and Comment as Message over the input field shares also the URL Key.)
 
A new "timeline" ("latest") button next to the seaerch button shows title of Message (URL), URL and underneath sorted referring comments like on Mastodon or Twitter (can be done in the same search tab).

(Optionally: Mastodon Servers are hybrid implemented and bridged to bring these messages (Message title plus URL, if given) into the node.)

Search results in URL-search get next "view locally" also a "show comments for this URL" link and a "create a comment" link, to show the comments for an URL/message/page - or to create one comment, tied with it.

Regards Lenny

![URL-Insertation_Window](https://github.com/textbrowser/spot-on/assets/141999753/34c46ccd-0d08-4645-9859-2ab7e3cf54b9)

<img width="960" alt="comments" src="https://github.com/textbrowser/spot-on/assets/141999753/a36dce2e-aa50-4059-a9dd-cb7888f455a4">

<img width="960" alt="urlwithtimeline" src="https://github.com/textbrowser/spot-on/assets/141999753/16ad0db0-0803-4d20-a145-012f1caade0a">

**Comment by textbrowser** [comment]
X is a toxic hellish landscape. Rather be a wretch in Elden Ring than write anything Twitter-like or even Reddit-like.
