### ISSUE TITLE
Win-64: MSVCR120.dll

### ISSUE THREAD

**Issue by bolzobrazil** [textbrowser/spot-on#37]
OS Windows 11 64 Bit generates with the last Win32 Release an error:
MSVCR120.dll is missing.

The in the ZIP provided vcredist_x86.exe does not start under Win 11 64 Bit:
https://github.com/textbrowser/spot-on/releases/download/2023.01.15/Spot-On.zip

Here is the installable Win32 vcredist_x86.exe, which needs to be installed on OS Windows 11 64 Bit (also any Win Webserver)

https://download.microsoft.com/download/2/E/6/2E61CFA4-993B-4DD4-91DA-3737CD5CD6E3/vcredist_x86.exe

Ideally both, the Win64 vcredist_x64.exe is also installed:
https://download.microsoft.com/download/2/E/6/2E61CFA4-993B-4DD4-91DA-3737CD5CD6E3/vcredist_x64.exe

Haven't taken the Hash of both vcredist_x64.exe, but it should be a new one, as the one in the ZIP does not start.

Probably release a new Win-32-Zip (the Zip) with the date of 2023.01.15 under
the name Spot-On-Win32-Lib-Update.zip - just with both updated vcredist files:

https://github.com/textbrowser/spot-on/releases/download/2023.01.15/Spot-On-Win32-Lib-Update.zip

Thanks

**Comment by textbrowser** [comment]
Not mentioned anywhere in https://doc.qt.io/qt-6/windows-deployment.html.

**Comment by textbrowser** [comment]
Maybe, probably, perhaps OpenSSL libraries. I have a task to undo OpenSSL because it's impossible to maintain and I've lost interest in doing so.

Also, account farming is bad. Bad people do it.
