### ISSUE TITLE
RSS-Feed on the Web-Search Webinterface page

### ISSUE THREAD

**Issue by Sammysupport** [textbrowser/spot-on#40]
Hello,

would it be a convenient and practical feature request to please provide a RSS-Feed-URL (with/via RSS-icon) on the HTML-Page for the Websearch Webinterface. Users can then download via RSS the "Timeline" of such an search instance into their own Spot-On Instance - via RSS! and they need not to exchange a key from the app or over the webpage, as requested in #39.

Thanks!

**Comment by textbrowser** [comment]
http://web.archive.org/

SO is just a tiny subset of that without an implicit search without an implicit catalog without an implicit interface. The data has organization and just dares you to be clever about it.

**Comment by Sammysupport** [comment]
nah, we leave that to Mr. D.

**Comment by textbrowser** [comment]
SF offers server-side scripting.

https://sourceforge.net/p/forge/documentation/Project%20Web%20and%20Developer%20Web/#cgi-script-support

Being clever is, well, clever.

https://github.com/textbrowser/spot-on-shared-pages

1. Fork a repository.
2. Create a cyclic indexing script based on the content of the forked repository.
3. Upload the index (indices) to GH or SF.
4. A server-side interface queries the indices, either through a database or through files.

But you know, thinking and work. Clever. That's it. Thinking, curious, evolve.

**Comment by textbrowser** [comment]
Delegation is easy. Is cheap. Costs a bunch of "ideas" for others. Others have ideas before you have ideas, idea that? The world is not a nebulous group of simpletons. People idea but don't scream about it.

**Comment by textbrowser** [comment]
Silly request anyway. I want to search Google but now I need a key although the data is not private. The shared pages not be private. They be there. If they private, would not be shared in plain form because they would be silly and meaningless. They shared. How you interpret the rest it left on you. Many easy solutions none involving keys and timelines.
