### ISSUE TITLE
Manual entries into the URL database.

### ISSUE THREAD

**Issue by Sammysupport** [textbrowser/spot-on#42]
Search engines have narrowed to just a few global players like Google, Bing, and Yandex. 
Google's censorship is already visible on Yandex as it sorts new URLs out, until Yandex is doing it as well.

A few days ago ChatGPT-Search launched (it might has importance like the chrome founding), and in a few months, Bing and Gemini AI will shift us from keyword searches to specific questions, to which AI instantly presents elaborated articles as answers.

Wikipedia editors are becoming obsolete as articles are created live and instantly in any language.

If one of the three main players censors a keyword or a topic, that's it. Is this a dystopia when the educational personnel denies the answer? It is like all books in one place ready to burn? We guess that's why each school and city should have a library. Local instances are the gatekeepers of the future.

We see decentralized storage of web indexes and URLs is now growing in importance.
Some countries support already ideas in this regard: https://openwebsearch.eu/

At the same time, creating blog news requires complex infrastructure, as does adding an URL to Spot-On (e.g. setting up feed aggregators on a website).

To simplify, the following streamlined process is probably helpful ( - so it is not an enhancement request for more library-specific or PDF-specific DB-additions).

**Spot-On could provide a tab or button-pop-up-window for the manual entry into the URL database of:** 
- **URL (if needed or available),** 
- **Title,** 
- **and Newstext (in plaintext or richtext format, not html).**

(To have the data indexed by keywords, the 3-lines-form could be also in a sub-tab of the RSS Tool).

That´s an idea for URLs and News Search. 
Many thanks.

**Comment by textbrowser** [comment]
Good idea? We just don't know!

**Comment by textbrowser** [comment]
Better idea.

Install Apache. Local or remote.
Create standard RSS with local links.
Every day, all day, create sponges of information.

https://127.0.0.1/my-local-rss-feed
https://127.0.0.1/my-local-link-1

Spot-On? Read and populate. All you do can do to improve life.

Closing!

**Comment by textbrowser** [comment]
https://www.linode.com/docs/guides/host-your-own-rss-reader-with-tiny-tiny-rss-on-centos-7/

**Comment by textbrowser** [comment]
We was waiting for you to realize a better idea existed before posting the better idea. Clear, concise, Spot-On remains free of nonsense, and educational of experience. Learn and educate and proceed with self-insight. No more tickets!

**Comment by textbrowser** [comment]
https://tt-rss.org/

And is tiny fit inside a Pi or Arduino. Tiny and Spot-On reads and no big hands required.

**Comment by textbrowser** [comment]
Yo Sammy of the Duplicates.

This be available in December with published pages. Dooble has it. Others will not. But you can do it. YOU can do it.

Title
URL
Data

-or-

URL
Title
Data

In a file and in a directory. Then you just Options -> Miscellaneous -> PUBLISHED_PAGES and YOU are done. See YOU.

**Comment by textbrowser** [comment]
Import published pages. Options -> Miscellaneous. Importing occurs routinely. (PUBLISHED_PAGES := path, title-line-number, url-line-number)

See YOU!
