### ISSUE TITLE
Add support for Matrix protocol

### ISSUE THREAD

**Issue by homebeach** [textbrowser/spot-on#5]
Add support for Matrix protocol. For example a bridge between Echo and [Matrix](https://matrix.org). Here is corresponding issue in Matrix wishlist: https://github.com/turt2live/matrix-wishlist/issues/151.

**Comment by textbrowser** [comment]
Alright! A new ticket! Thank you.

**Comment by homebeach** [comment]
Here is the Matrix FAQ: https://matrix.org/docs/guides/faq and here is the specification: https://matrix.org/docs/spec/. I would say that supporthing these kinds of standard protocols is worth it.

**Comment by textbrowser** [comment]
Does Matrix function without registration? Like, I'd like to send some data to a destination without having to describe that destination to anyone but the destination. Can I do that?

**Comment by homebeach** [comment]
There is support for guest accounts.

**Comment by textbrowser** [comment]
That requires registration, right?

**Comment by homebeach** [comment]
It should be possible to send without registration.

**Comment by sjehuda** [comment]
Please add **Jabber/XMPP** to title: Add support for Matrix and XMPP protocols

**Comment by sjehuda** [comment]
@textbrowser Does Spot-on support XMPP messaging?

**Comment by textbrowser** [comment]
If it ain't listed, it ain't present. XMPP is dead and full of suspicious problems. Jabberwocky replaced it. No more Jabber.

**Comment by sjehuda** [comment]
What does "Jabberwocky" mean?

**Comment by textbrowser** [comment]
It's a creature from a nonsensical poem written many years ago by the insane man who wrote about Alice and her wonder-less wonderland. Alice is quite popular in the world of cryptography. And there is Jabber. So, natural relationship about nonsense and Alice and wonky and Jabber.
