### ISSUE TITLE
A more detailed README.md

### ISSUE THREAD

**Issue by dud1337** [textbrowser/spot-on#6]
I'm curious about your project, but I really do not understand what it does yet.
>"Spot-On is an interstellar dolphin-propelled science vessel sailing on the winds of chaos. Now with Ultra StarBeams!"

It's a search engine, email and chat client?

This is a separate issue, but if you also create GoldBug, could you host that on GitHub or GitLab, too? SourceForge is a pain to read through.

**Comment by textbrowser** [comment]
E-mail, text, search engine, pass-through device, may contain collections of Web pages, may be used to attach TLS to non-TLS software (depends on the software), file sharing, directory / file encrypting, pad-like encryption, texting through IMAP / POP3, group communications, etc.

I do not own GoldBug, however, I do maintain its UI files.

Thank you for the interest.

**Comment by dud1337** [comment]
Cheers for the response! I still think it could use a more fleshed-out README, but it's your call if you want to close this issue or not.

**Comment by textbrowser** [comment]
Done! Thanks.

**Comment by sjehuda** [comment]
Please also define this program in general with a few sentences.

From the documentation

> Spot-On is a dolphin-propelled science project. The software is composed of two separate applications, a multitasking kernel and an operator interface. The two applications are written in C++ and require the Qt framework as well as an assortment of libraries. Qt versions Qt 5.x are supported. Spot-On is available on FreeBSD, Linux, OS X, OS/2, and Windows. In addition to supporting the x86 and x86-64 architectures, ARM, PowerPC, and SPARC are supported without any special provisions. Qt version 4.8.7 may be functional although it is not supported.
> 
> Please note that the Echo algorithm and its name are not derived from Ernest J. H. Chang's 1982 Echo Algorithms: Depth Parallel Operations on General Graphs paper.
