### ISSUE TITLE
Unable to register for Account.  FB and email 

### ISSUE THREAD

**Issue by KKenui** [textbrowser/spot-on#7]

**Comment by textbrowser** [comment]
Spot-On doesn't exist on Android.

**Comment by KKenui** [comment]
The link is incorrect then on Source Forge


Smoke is an encrypting chat messenger for Android written in Java.

Please read the Web site for more information:
https://smokeappope.sourceforge.io/

Smoke App OPE - Online Poem Encryption

Download Android APK Installer:
https://sourceforge.net/projects/smokeappope/files/

Smoke Source:
https://github.com/textbrowser/smoke

SmokeStack Source:
https://github.com/textbrowser/smokestack (Android)
https://github.com/textbrowser/spot-on (Desktop)

**Comment by textbrowser** [comment]
Ah, that's Smoke! This is Spot-On.

**Comment by textbrowser** [comment]
Smoke is not yet in the Play Store.

**Comment by textbrowser** [comment]
I don't maintain https://smokeappope.sourceforge.io/.
